#!/bin/bash
set -e

cp -r /usr/share/loolwsd /opt/static
setcap "cap_sys_chroot=ep cap_mknod=ep cap_fowner=ep" /usr/bin/loolforkit

su lool -s /bin/sh -c /usr/bin/loolwsd  -- --version --o:sys_template_path=/opt/lool/systemplate --o:lo_template_path=/opt/collaboraoffice6.0 --o:child_root_path=/opt/lool/child-roots --o:file_server_root_path=/opt/storage/files


