robocup-humanoid:
  adapter: postgresql
  prepared_statements: false
  database: robocup_humanoid
  username: robocup_discourse
  password: pw
  host: localhost
  port: 6432
  pool: 5
  timeout: 5000
  db_id: 2	# ensure db_id is unique for each site
  ### If you change this setting you will need to
  ###   - restart sidekiq if you change this setting
  ###   - rebake all to posts using: `RAILS_ENV=production bundle exec rake posts:rebake`
  host_names:
    - forum.bit-bots.de
    - discourse.robocup-humanoid.org
    - forum.robocup-humanoid.org

