---
kind: pipeline
type: kubernetes
name: base-buster
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/base-buster
      username: agserver
      password:
        from_secret: REGISTRY_PW

