---
kind: pipeline
type: kubernetes
name: base-buster
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/base-buster
      username: agserver
      password:
        from_secret: REGISTRY_PW
      context: base-buster
      dockerfile: base-buster/Dockerfile

---
kind: pipeline
type: kubernetes
name: base-stretch
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/base-stretch
      username: agserver
      password:
        from_secret: REGISTRY_PW
      context: base-stretch
      dockerfile: base-stretch/Dockerfile

---
kind: pipeline
type: kubernetes
name: nextcloud
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/nextcloud
      username: agserver
      password:
        from_secret: REGISTRY_PW
      context: nextcloud
      dockerfile: nextcloud/Dockerfile
  - name: restart deployment
    image: registry.mafiasi.de/deployment_restarter
    settings:
      namespace: mafiasi-prod
      name: mafiasi-cloud

---
kind: pipeline
type: kubernetes
name: collaboraoffice
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/collaboraoffice
      username: agserver
      password:
        from_secret: REGISTRY_PW
      context: collaboraoffice
      dockerfile: collaboraoffice/Dockerfile

---
kind: pipeline
type: kubernetes
name: mattermost
trigger:
  branch:
    - master

steps:
  - name: update container
    image: plugins/docker
    settings:
      registry: registry.mafiasi.de
      repo: registry.mafiasi.de/mattermost
      username: agserver
      password:
        from_secret: REGISTRY_PW
      context: mattermost
      dockerfile: mattermost/Dockerfile
      tags: 5.26.2
      build_args:
        - VERSION=5.26.2
  - name: restart deployment
    image: registry.mafiasi.de/deployment_restarter
    settings:
      namespace: mafiasi-prod
      name: mafiasi-mattermost
