#! /bin/bash

VERSION=0.0.1
NAME=oe-stammbaum
IMAGE_NAME=$NAME-$VERSION-linux-amd64.aci
echo "Building $IMAGE_NAME"

rm -v $IMAGE_NAME

. acbuildhelper.sh

acbuild set-name rkt.mafiasi.de/$NAME
acbuild dependency add rkt.mafiasi.de/python-uwsgi
source .acbuild/current/rootfs/opt/py-env/bin/activate 
# TODO!!!
cp /home/nils/git/dudel-django .acbuild/current/rootfs/opt/stammbaum
pip install -r .acbuild/current/rootfs/opt/stammbaum/requirements.txt

echo """
[uwsgi]
chdir=/opt/stammbaum/
wsgi-file=stammbaum/wsgi.py
""" > .acbuild/current/rootfs/opt/uwsgi.app.conf
acbuild set-exec -- /opt/py-env/bin/uwsgi /opt/uwsgi.defaults.conf

acbuild write $IMAGE_NAME
sudo -su nils gpg --default-key E4CA7691 --armor --output $IMAGE_NAME.asc --detach-sign $IMAGE_NAME 
