<?php
$CONFIG = array (
  'instanceid' => 'TO_BE_INSERTED',
  'passwordsalt' => 'TO_BE_INSERTED',
  'secret' => 'TO_BE_INSERTED',
  'trusted_domains' =>
  array (
    0 => 'owncloud.crossmodal-learning.org',
    1 => 'owncloud.mafiasi.de',
  ),
  'datadirectory' => '/opt/storage',
  'dbtype' => 'pgsql',
  'version' => '8.2.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'tams-cml.informatik.uni-hamburg.de:6432',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'TO_BE_INSERTED',
  'installed' => true,
  'forcessl' => false,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 1,
  'logfile' => '/opt/log/owncloud.log',
  'theme' => 'mafiasi',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'tams-cml.informatik.uni-hamburg.de',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'crossmodal-learning.org',
  'maintenance' => false,
  'minimum.supported.desktop.version' => '1.5',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
	  array (
		'host' => 'localhost',
		'port' => 6380,
		'timeout' => 0,
		'password' => '',
	  ),
  'trashbin_retention_obligation' => 'auto',
);
