#!/bin/sh
export USER=www-data HOME=/opt/dashboard/
cp -rT /usr/share/javascript/mathjax /opt/static/mathjax
python3 /opt/dashboard/manage.py migrate
cd /opt/dashboard
make
mkdir /opt/static/django
python3 /opt/dashboard/manage.py collectstatic --no-input
exec uwsgi /etc/uwsgi/dashboard.ini

