#!/bin/sh
set -e

if grep -i "START_SSH_SERVER *= *false" /opt/config/app.ini; then
    echo AuthorizedKeysFile .ssh/id_ed25519.pub >> /etc/ssh/sshd_config
    service ssh start
fi

hostname -I > /opt/storage/gitea.ip

su git -s /bin/sh -c "/opt/gitea/gitea web"

