#!/bin/bash
export USER=www-data HOME=/home/www-data
export PYTHONPATH=/opt/ros/melodic/lib/python2.7/dist-packages:/opt/marv/venv/lib/python2.7/site-packages

# Actually start the server
exec uwsgi --ini /etc/uwsgi/marv.ini
