#!/bin/bash
export USER=www-data HOME=/home/www-data
source /opt/ros/melodic/setup.bash
cd /opt/config
# Scan for new bags
marv scan
marv run --collection=bags
# Remove deleted bags from database
MISSING_BAGS=$(marv query --missing)
[[ -n "$MISSING_BAGS"]] && marv discard $MISSING_BAGS
