#!/bin/sh -e
. /usr/share/GNUstep/Makefiles/GNUstep.sh

install -o sogo -g nogroup -m 755 -d /var/run/sogo
install -o sogo -g nogroup -m 750 -d /var/log/sogo

chown sogo /opt/log

# copy static
cp -r /usr/local/lib/GNUstep/SOGo/WebServerResources/* /opt/static/

export USER=sogo HOME=/home/sogo
tail -F /opt/log/sogo.log &
exec uwsgi --ini /etc/uwsgi/sogo.ini
