name: build_single_container
on:
  workflow_dispatch:
    inputs:
      container:
        description: Which container to build
        type: string
        required: true
  workflow_call:
    inputs:
      container:
        description: Which container to build
        type: string
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build_container:
    name: Build ${{ inputs.container }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.container }}
          push: true
          tags: ghcr.io/fsinfuhh/${{ inputs.container }}:latest
          labels: |
            org.opencontainers.image.title=${{ inputs.container }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
