name: build all containers
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * 1"   # every monday

permissions:
  contents: read
  packages: write

jobs:
  build_all_containers:
    name: Build App Containers
    strategy:
      fail-fast: false
      matrix:
        container:
          - etherpad
          - limesurvey
          - nextcloud
          - sogo
    uses: ./.github/workflows/build_single_container.yml
    secrets: inherit
    with:
      container: ${{ matrix.container }}
