FROM docker://debian:buster-slim

COPY sources.list /etc/apt/sources.list
RUN apt update; apt upgrade --yes
RUN apt install --yes --no-install-recommends vim ca-certificates
RUN apt-get clean
RUN mkdir -p /opt/config /opt/storage /opt/log

ENTRYPOINT /bin/bash